install:
  - appveyor DownloadFile https://strcpy.net/packages/Win32OpenSSL-1_0_2a.exe 
  - Win32OpenSSL-1_0_2a.exe /silent /verysilent /sp- /suppressmsgboxes
build_script:
  - md build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest --output-on-failure
cache:
  - C:\OpenSSL-Win32
